### ISSUE TITLE
novaconsole command not found

### ISSUE THREAD

**Issue by rainleander** [equinix/terraform-metal-openstack#36]
What were you trying to do:
Open the novaconsole via https://github.com/packet-labs/OpenStackOnPacket#serial-console-support

What steps did you take to do it:
source admin-openrc
openstack console url show --serial Xenial-arm64
novaconsole --url ws://147.75.101.55:6083/?token=8f57618b-560f-4c39-ab63-8c4357712f3e

What did you expect to happen:
The novaconsole opens

What happened:
-bash: novaconsole: command not found

**Comment by johnstudarus** [comment]
nova-console rather than novaconsole. Looks like you need the '-'.

**Comment by johnstudarus** [comment]
For x86 machines, you don't need to use novaconsole, it is an ARM thing only. For x86 machines, you can pull up the console via the GUI.

novaconsole isn't being installed right now (TF files is off). You can turn it back on by renaming the file from NovaConsole.tf.off to NovaConsole.tf. But it is only needed for ARM systems since the regular GUI doesn't work for ARM systems.

https://github.com/packet-labs/OpenStackOnPacket/blob/master/NovaConsole.tf.off

**Comment by johnstudarus** [comment]
Looks like novaconsole isn't needed anymore as ARM console support is now available in the main code base.

https://marcin.juszkiewicz.com.pl/2018/02/06/graphical-console-in-openstack-aarch64/

The step around using novaconsole should be removed from the docs.

**Comment by displague** [comment]
NovaConsole.tf has been removed from the project.

@jmarhee Is that sufficient or do we need to revisit any of the README.md content to reflect these changes before closing this?

**Comment by jmarhee** [comment]
Only https://github.com/equinix/terraform-metal-openstack#serial-console-support needs to be removed. Will check into this to be sure.
